In [2]:
import numpy as np

# Imputer is deprecated.
#from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer

# For reproducibility
np.random.seed(1000)

In [3]:
data = np.array([[1, np.nan, 2], [2, 3, np.nan], [-1, 4, 2]])
print(data)

[[ 1. nan  2.]
 [ 2.  3. nan]
 [-1.  4.  2.]]


In [4]:
# Imputer with mean-strategy
print('Mean strategy')
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
print(imp.fit_transform(data))

Mean strategy
[[ 1.   3.5  2. ]
 [ 2.   3.   2. ]
 [-1.   4.   2. ]]


In [5]:
# Imputer with median-strategy
print('Median strategy')
imp = SimpleImputer(strategy='median')
print(imp.fit_transform(data))

Median strategy
[[ 1.   3.5  2. ]
 [ 2.   3.   2. ]
 [-1.   4.   2. ]]


In [6]:
# Imputer with most-frequent-strategy
print('Most-frequent strategy')
imp = SimpleImputer(strategy='most_frequent')
print(imp.fit_transform(data))

Most-frequent strategy
[[ 1.  3.  2.]
 [ 2.  3.  2.]
 [-1.  4.  2.]]
